#ifndef __DATA_TYPES_H__
#define __DATA_TYPES_H__

#include "Common.h"

enum DataTypeID
{
	DATA_TYPEID_BASIC				= 0,
	DATA_TYPEID_WORLDOBJECT,
	DATA_TYPEID_UNIT,
	DATA_TYPEID_PLAYER,
	DATA_TYPEID_ROBOT,
	DATA_TYPEID_ITEMBOX,
	DATA_TYPEID_ITEM,
	DATA_TYPEID_CARRIED_ITEM,
	DATA_TYPEID_PROJECTILE,
	DATA_TYPEID_OBJECT_LOCATOR,
	DATA_TYPEID_UNIT_LOCATOR,
};

enum DataTypeMask
{
	DATA_TYPEMASK_BASIC				= 1 << 0,
	DATA_TYPEMASK_WORLDOBJECT		= 1 << 1,
	DATA_TYPEMASK_UNIT				= 1 << 2,
	DATA_TYPEMASK_PLAYER			= 1 << 3,
	DATA_TYPEMASK_ROBOT				= 1 << 4,
	DATA_TYPEMASK_ITEMBOX			= 1 << 5,
	DATA_TYPEMASK_ITEM				= 1 << 6,
	DATA_TYPEMASK_CARRIED_ITEM		= 1 << 7,
	DATA_TYPEMASK_PROJECTILE		= 1 << 8,
	DATA_TYPEMASK_LOCATOR_OBJECT	= 1 << 9,
	DATA_TYPEMASK_UNIT_LOCATOR		= 1 << 10,
};

#endif // __DATA_TYPES_H__