#ifndef __UNIT_SLOT_DEFINES_H__
#define __UNIT_SLOT_DEFINES_H__

enum EquipmentSlots
{
	EQUIPMENT_SLOT_START				= 0,
	EQUIPMENT_SLOT_HAT					= EQUIPMENT_SLOT_START,
	EQUIPMENT_SLOT_JACKET,
	EQUIPMENT_SLOT_GLOVES,
	EQUIPMENT_SLOT_SNOWBALL_MAKER,
	EQUIPMENT_SLOT_SHOES,
	EQUIPMENT_SLOT_END,
};

#define INVENTORY_CUSTOM_SLOTS_COUNT	3

enum InventorySlots
{
	INVENTORY_SLOT_START				= EQUIPMENT_SLOT_END,
	INVENTORY_SLOT_CUSTOM_START			= INVENTORY_SLOT_START,
	INVENTORY_SLOT_CUSTOM_END			= INVENTORY_SLOT_CUSTOM_START + INVENTORY_CUSTOM_SLOTS_COUNT,
	INVENTORY_SLOT_FIRST_AID			= INVENTORY_SLOT_CUSTOM_END,
	INVENTORY_SLOT_END,
};

#define UNIT_SLOTS_COUNT				INVENTORY_SLOT_END
#define SLOT_INVALID					-1

#endif // __UNIT_SLOT_DEFINES_H__