// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthChallenge.proto

#ifndef PROTOBUF_AuthChallenge_2eproto__INCLUDED
#define PROTOBUF_AuthChallenge_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
class AuthChallenge;
class AuthChallengeDefaultTypeInternal;
extern AuthChallengeDefaultTypeInternal _AuthChallenge_default_instance_;

namespace protobuf_AuthChallenge_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_AuthChallenge_2eproto

// ===================================================================

class AuthChallenge : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:AuthChallenge) */ {
 public:
  AuthChallenge();
  virtual ~AuthChallenge();

  AuthChallenge(const AuthChallenge& from);

  inline AuthChallenge& operator=(const AuthChallenge& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AuthChallenge(AuthChallenge&& from) noexcept
    : AuthChallenge() {
    *this = ::std::move(from);
  }

  inline AuthChallenge& operator=(AuthChallenge&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const AuthChallenge& default_instance();

  static inline const AuthChallenge* internal_default_instance() {
    return reinterpret_cast<const AuthChallenge*>(
               &_AuthChallenge_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(AuthChallenge* other);
  friend void swap(AuthChallenge& a, AuthChallenge& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AuthChallenge* New() const PROTOBUF_FINAL { return New(NULL); }

  AuthChallenge* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const AuthChallenge& from);
  void MergeFrom(const AuthChallenge& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AuthChallenge* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 auth_seed = 1;
  void clear_auth_seed();
  static const int kAuthSeedFieldNumber = 1;
  ::google::protobuf::uint32 auth_seed() const;
  void set_auth_seed(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:AuthChallenge)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::uint32 auth_seed_;
  mutable int _cached_size_;
  friend struct protobuf_AuthChallenge_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AuthChallenge

// uint32 auth_seed = 1;
inline void AuthChallenge::clear_auth_seed() {
  auth_seed_ = 0u;
}
inline ::google::protobuf::uint32 AuthChallenge::auth_seed() const {
  // @@protoc_insertion_point(field_get:AuthChallenge.auth_seed)
  return auth_seed_;
}
inline void AuthChallenge::set_auth_seed(::google::protobuf::uint32 value) {
  
  auth_seed_ = value;
  // @@protoc_insertion_point(field_set:AuthChallenge.auth_seed)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_AuthChallenge_2eproto__INCLUDED
