// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BattleUpdate.proto

#ifndef PROTOBUF_BattleUpdate_2eproto__INCLUDED
#define PROTOBUF_BattleUpdate_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
class BattleUpdate;
class BattleUpdateDefaultTypeInternal;
extern BattleUpdateDefaultTypeInternal _BattleUpdate_default_instance_;

namespace protobuf_BattleUpdate_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_BattleUpdate_2eproto

// ===================================================================

class BattleUpdate : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:BattleUpdate) */ {
 public:
  BattleUpdate();
  virtual ~BattleUpdate();

  BattleUpdate(const BattleUpdate& from);

  inline BattleUpdate& operator=(const BattleUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BattleUpdate(BattleUpdate&& from) noexcept
    : BattleUpdate() {
    *this = ::std::move(from);
  }

  inline BattleUpdate& operator=(BattleUpdate&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const BattleUpdate& default_instance();

  static inline const BattleUpdate* internal_default_instance() {
    return reinterpret_cast<const BattleUpdate*>(
               &_BattleUpdate_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(BattleUpdate* other);
  friend void swap(BattleUpdate& a, BattleUpdate& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BattleUpdate* New() const PROTOBUF_FINAL { return New(NULL); }

  BattleUpdate* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const BattleUpdate& from);
  void MergeFrom(const BattleUpdate& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BattleUpdate* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 update_flags = 1;
  void clear_update_flags();
  static const int kUpdateFlagsFieldNumber = 1;
  ::google::protobuf::uint32 update_flags() const;
  void set_update_flags(::google::protobuf::uint32 value);

  // uint32 state = 2;
  void clear_state();
  static const int kStateFieldNumber = 2;
  ::google::protobuf::uint32 state() const;
  void set_state(::google::protobuf::uint32 value);

  // int32 start_time = 3;
  void clear_start_time();
  static const int kStartTimeFieldNumber = 3;
  ::google::protobuf::int32 start_time() const;
  void set_start_time(::google::protobuf::int32 value);

  // int32 preparation_duration = 4;
  void clear_preparation_duration();
  static const int kPreparationDurationFieldNumber = 4;
  ::google::protobuf::int32 preparation_duration() const;
  void set_preparation_duration(::google::protobuf::int32 value);

  // int32 battle_duration = 5;
  void clear_battle_duration();
  static const int kBattleDurationFieldNumber = 5;
  ::google::protobuf::int32 battle_duration() const;
  void set_battle_duration(::google::protobuf::int32 value);

  // int32 alive_count = 6;
  void clear_alive_count();
  static const int kAliveCountFieldNumber = 6;
  ::google::protobuf::int32 alive_count() const;
  void set_alive_count(::google::protobuf::int32 value);

  // int32 magicbean_count = 7;
  void clear_magicbean_count();
  static const int kMagicbeanCountFieldNumber = 7;
  ::google::protobuf::int32 magicbean_count() const;
  void set_magicbean_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:BattleUpdate)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::uint32 update_flags_;
  ::google::protobuf::uint32 state_;
  ::google::protobuf::int32 start_time_;
  ::google::protobuf::int32 preparation_duration_;
  ::google::protobuf::int32 battle_duration_;
  ::google::protobuf::int32 alive_count_;
  ::google::protobuf::int32 magicbean_count_;
  mutable int _cached_size_;
  friend struct protobuf_BattleUpdate_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BattleUpdate

// uint32 update_flags = 1;
inline void BattleUpdate::clear_update_flags() {
  update_flags_ = 0u;
}
inline ::google::protobuf::uint32 BattleUpdate::update_flags() const {
  // @@protoc_insertion_point(field_get:BattleUpdate.update_flags)
  return update_flags_;
}
inline void BattleUpdate::set_update_flags(::google::protobuf::uint32 value) {
  
  update_flags_ = value;
  // @@protoc_insertion_point(field_set:BattleUpdate.update_flags)
}

// uint32 state = 2;
inline void BattleUpdate::clear_state() {
  state_ = 0u;
}
inline ::google::protobuf::uint32 BattleUpdate::state() const {
  // @@protoc_insertion_point(field_get:BattleUpdate.state)
  return state_;
}
inline void BattleUpdate::set_state(::google::protobuf::uint32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:BattleUpdate.state)
}

// int32 start_time = 3;
inline void BattleUpdate::clear_start_time() {
  start_time_ = 0;
}
inline ::google::protobuf::int32 BattleUpdate::start_time() const {
  // @@protoc_insertion_point(field_get:BattleUpdate.start_time)
  return start_time_;
}
inline void BattleUpdate::set_start_time(::google::protobuf::int32 value) {
  
  start_time_ = value;
  // @@protoc_insertion_point(field_set:BattleUpdate.start_time)
}

// int32 preparation_duration = 4;
inline void BattleUpdate::clear_preparation_duration() {
  preparation_duration_ = 0;
}
inline ::google::protobuf::int32 BattleUpdate::preparation_duration() const {
  // @@protoc_insertion_point(field_get:BattleUpdate.preparation_duration)
  return preparation_duration_;
}
inline void BattleUpdate::set_preparation_duration(::google::protobuf::int32 value) {
  
  preparation_duration_ = value;
  // @@protoc_insertion_point(field_set:BattleUpdate.preparation_duration)
}

// int32 battle_duration = 5;
inline void BattleUpdate::clear_battle_duration() {
  battle_duration_ = 0;
}
inline ::google::protobuf::int32 BattleUpdate::battle_duration() const {
  // @@protoc_insertion_point(field_get:BattleUpdate.battle_duration)
  return battle_duration_;
}
inline void BattleUpdate::set_battle_duration(::google::protobuf::int32 value) {
  
  battle_duration_ = value;
  // @@protoc_insertion_point(field_set:BattleUpdate.battle_duration)
}

// int32 alive_count = 6;
inline void BattleUpdate::clear_alive_count() {
  alive_count_ = 0;
}
inline ::google::protobuf::int32 BattleUpdate::alive_count() const {
  // @@protoc_insertion_point(field_get:BattleUpdate.alive_count)
  return alive_count_;
}
inline void BattleUpdate::set_alive_count(::google::protobuf::int32 value) {
  
  alive_count_ = value;
  // @@protoc_insertion_point(field_set:BattleUpdate.alive_count)
}

// int32 magicbean_count = 7;
inline void BattleUpdate::clear_magicbean_count() {
  magicbean_count_ = 0;
}
inline ::google::protobuf::int32 BattleUpdate::magicbean_count() const {
  // @@protoc_insertion_point(field_get:BattleUpdate.magicbean_count)
  return magicbean_count_;
}
inline void BattleUpdate::set_magicbean_count(::google::protobuf::int32 value) {
  
  magicbean_count_ = value;
  // @@protoc_insertion_point(field_set:BattleUpdate.magicbean_count)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_BattleUpdate_2eproto__INCLUDED
