// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BattleResult.proto

#ifndef PROTOBUF_BattleResult_2eproto__INCLUDED
#define PROTOBUF_BattleResult_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
class BattleResult;
class BattleResultDefaultTypeInternal;
extern BattleResultDefaultTypeInternal _BattleResult_default_instance_;

namespace protobuf_BattleResult_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_BattleResult_2eproto

// ===================================================================

class BattleResult : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:BattleResult) */ {
 public:
  BattleResult();
  virtual ~BattleResult();

  BattleResult(const BattleResult& from);

  inline BattleResult& operator=(const BattleResult& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BattleResult(BattleResult&& from) noexcept
    : BattleResult() {
    *this = ::std::move(from);
  }

  inline BattleResult& operator=(BattleResult&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const BattleResult& default_instance();

  static inline const BattleResult* internal_default_instance() {
    return reinterpret_cast<const BattleResult*>(
               &_BattleResult_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(BattleResult* other);
  friend void swap(BattleResult& a, BattleResult& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BattleResult* New() const PROTOBUF_FINAL { return New(NULL); }

  BattleResult* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const BattleResult& from);
  void MergeFrom(const BattleResult& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BattleResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 outcome = 1;
  void clear_outcome();
  static const int kOutcomeFieldNumber = 1;
  ::google::protobuf::uint32 outcome() const;
  void set_outcome(::google::protobuf::uint32 value);

  // int32 kill_count = 2;
  void clear_kill_count();
  static const int kKillCountFieldNumber = 2;
  ::google::protobuf::int32 kill_count() const;
  void set_kill_count(::google::protobuf::int32 value);

  // int32 rank_no = 3;
  void clear_rank_no();
  static const int kRankNoFieldNumber = 3;
  ::google::protobuf::int32 rank_no() const;
  void set_rank_no(::google::protobuf::int32 value);

  // int32 money = 4;
  void clear_money();
  static const int kMoneyFieldNumber = 4;
  ::google::protobuf::int32 money() const;
  void set_money(::google::protobuf::int32 value);

  // uint32 level = 5;
  void clear_level();
  static const int kLevelFieldNumber = 5;
  ::google::protobuf::uint32 level() const;
  void set_level(::google::protobuf::uint32 value);

  // int32 experience = 6;
  void clear_experience();
  static const int kExperienceFieldNumber = 6;
  ::google::protobuf::int32 experience() const;
  void set_experience(::google::protobuf::int32 value);

  // int32 extra_money = 7;
  void clear_extra_money();
  static const int kExtraMoneyFieldNumber = 7;
  ::google::protobuf::int32 extra_money() const;
  void set_extra_money(::google::protobuf::int32 value);

  // int32 extra_xp = 8;
  void clear_extra_xp();
  static const int kExtraXpFieldNumber = 8;
  ::google::protobuf::int32 extra_xp() const;
  void set_extra_xp(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:BattleResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::uint32 outcome_;
  ::google::protobuf::int32 kill_count_;
  ::google::protobuf::int32 rank_no_;
  ::google::protobuf::int32 money_;
  ::google::protobuf::uint32 level_;
  ::google::protobuf::int32 experience_;
  ::google::protobuf::int32 extra_money_;
  ::google::protobuf::int32 extra_xp_;
  mutable int _cached_size_;
  friend struct protobuf_BattleResult_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BattleResult

// uint32 outcome = 1;
inline void BattleResult::clear_outcome() {
  outcome_ = 0u;
}
inline ::google::protobuf::uint32 BattleResult::outcome() const {
  // @@protoc_insertion_point(field_get:BattleResult.outcome)
  return outcome_;
}
inline void BattleResult::set_outcome(::google::protobuf::uint32 value) {
  
  outcome_ = value;
  // @@protoc_insertion_point(field_set:BattleResult.outcome)
}

// int32 kill_count = 2;
inline void BattleResult::clear_kill_count() {
  kill_count_ = 0;
}
inline ::google::protobuf::int32 BattleResult::kill_count() const {
  // @@protoc_insertion_point(field_get:BattleResult.kill_count)
  return kill_count_;
}
inline void BattleResult::set_kill_count(::google::protobuf::int32 value) {
  
  kill_count_ = value;
  // @@protoc_insertion_point(field_set:BattleResult.kill_count)
}

// int32 rank_no = 3;
inline void BattleResult::clear_rank_no() {
  rank_no_ = 0;
}
inline ::google::protobuf::int32 BattleResult::rank_no() const {
  // @@protoc_insertion_point(field_get:BattleResult.rank_no)
  return rank_no_;
}
inline void BattleResult::set_rank_no(::google::protobuf::int32 value) {
  
  rank_no_ = value;
  // @@protoc_insertion_point(field_set:BattleResult.rank_no)
}

// int32 money = 4;
inline void BattleResult::clear_money() {
  money_ = 0;
}
inline ::google::protobuf::int32 BattleResult::money() const {
  // @@protoc_insertion_point(field_get:BattleResult.money)
  return money_;
}
inline void BattleResult::set_money(::google::protobuf::int32 value) {
  
  money_ = value;
  // @@protoc_insertion_point(field_set:BattleResult.money)
}

// uint32 level = 5;
inline void BattleResult::clear_level() {
  level_ = 0u;
}
inline ::google::protobuf::uint32 BattleResult::level() const {
  // @@protoc_insertion_point(field_get:BattleResult.level)
  return level_;
}
inline void BattleResult::set_level(::google::protobuf::uint32 value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:BattleResult.level)
}

// int32 experience = 6;
inline void BattleResult::clear_experience() {
  experience_ = 0;
}
inline ::google::protobuf::int32 BattleResult::experience() const {
  // @@protoc_insertion_point(field_get:BattleResult.experience)
  return experience_;
}
inline void BattleResult::set_experience(::google::protobuf::int32 value) {
  
  experience_ = value;
  // @@protoc_insertion_point(field_set:BattleResult.experience)
}

// int32 extra_money = 7;
inline void BattleResult::clear_extra_money() {
  extra_money_ = 0;
}
inline ::google::protobuf::int32 BattleResult::extra_money() const {
  // @@protoc_insertion_point(field_get:BattleResult.extra_money)
  return extra_money_;
}
inline void BattleResult::set_extra_money(::google::protobuf::int32 value) {
  
  extra_money_ = value;
  // @@protoc_insertion_point(field_set:BattleResult.extra_money)
}

// int32 extra_xp = 8;
inline void BattleResult::clear_extra_xp() {
  extra_xp_ = 0;
}
inline ::google::protobuf::int32 BattleResult::extra_xp() const {
  // @@protoc_insertion_point(field_get:BattleResult.extra_xp)
  return extra_xp_;
}
inline void BattleResult::set_extra_xp(::google::protobuf::int32 value) {
  
  extra_xp_ = value;
  // @@protoc_insertion_point(field_set:BattleResult.extra_xp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_BattleResult_2eproto__INCLUDED
