// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemUseResult.proto

#ifndef PROTOBUF_ItemUseResult_2eproto__INCLUDED
#define PROTOBUF_ItemUseResult_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
class ItemUseResult;
class ItemUseResultDefaultTypeInternal;
extern ItemUseResultDefaultTypeInternal _ItemUseResult_default_instance_;

namespace protobuf_ItemUseResult_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_ItemUseResult_2eproto

// ===================================================================

class ItemUseResult : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:ItemUseResult) */ {
 public:
  ItemUseResult();
  virtual ~ItemUseResult();

  ItemUseResult(const ItemUseResult& from);

  inline ItemUseResult& operator=(const ItemUseResult& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ItemUseResult(ItemUseResult&& from) noexcept
    : ItemUseResult() {
    *this = ::std::move(from);
  }

  inline ItemUseResult& operator=(ItemUseResult&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ItemUseResult& default_instance();

  static inline const ItemUseResult* internal_default_instance() {
    return reinterpret_cast<const ItemUseResult*>(
               &_ItemUseResult_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ItemUseResult* other);
  friend void swap(ItemUseResult& a, ItemUseResult& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ItemUseResult* New() const PROTOBUF_FINAL { return New(NULL); }

  ItemUseResult* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const ItemUseResult& from);
  void MergeFrom(const ItemUseResult& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ItemUseResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 status = 1;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // uint32 item = 2;
  void clear_item();
  static const int kItemFieldNumber = 2;
  ::google::protobuf::uint32 item() const;
  void set_item(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ItemUseResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::int32 status_;
  ::google::protobuf::uint32 item_;
  mutable int _cached_size_;
  friend struct protobuf_ItemUseResult_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ItemUseResult

// int32 status = 1;
inline void ItemUseResult::clear_status() {
  status_ = 0;
}
inline ::google::protobuf::int32 ItemUseResult::status() const {
  // @@protoc_insertion_point(field_get:ItemUseResult.status)
  return status_;
}
inline void ItemUseResult::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:ItemUseResult.status)
}

// uint32 item = 2;
inline void ItemUseResult::clear_item() {
  item_ = 0u;
}
inline ::google::protobuf::uint32 ItemUseResult::item() const {
  // @@protoc_insertion_point(field_get:ItemUseResult.item)
  return item_;
}
inline void ItemUseResult::set_item(::google::protobuf::uint32 value) {
  
  item_ = value;
  // @@protoc_insertion_point(field_set:ItemUseResult.item)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ItemUseResult_2eproto__INCLUDED
