// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemPickupResult.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ItemPickupResult.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
class ItemPickupResultDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ItemPickupResult>
     _instance;
} _ItemPickupResult_default_instance_;

namespace protobuf_ItemPickupResult_2eproto {

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _ItemPickupResult_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_ItemPickupResult_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}

}  // namespace protobuf_ItemPickupResult_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ItemPickupResult::kStatusFieldNumber;
const int ItemPickupResult::kItemFieldNumber;
const int ItemPickupResult::kRemainingTimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ItemPickupResult::ItemPickupResult()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_ItemPickupResult_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ItemPickupResult)
}
ItemPickupResult::ItemPickupResult(const ItemPickupResult& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&status_, &from.status_,
    static_cast<size_t>(reinterpret_cast<char*>(&remaining_time_) -
    reinterpret_cast<char*>(&status_)) + sizeof(remaining_time_));
  // @@protoc_insertion_point(copy_constructor:ItemPickupResult)
}

void ItemPickupResult::SharedCtor() {
  ::memset(&status_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&remaining_time_) -
      reinterpret_cast<char*>(&status_)) + sizeof(remaining_time_));
  _cached_size_ = 0;
}

ItemPickupResult::~ItemPickupResult() {
  // @@protoc_insertion_point(destructor:ItemPickupResult)
  SharedDtor();
}

void ItemPickupResult::SharedDtor() {
}

void ItemPickupResult::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ItemPickupResult& ItemPickupResult::default_instance() {
  protobuf_ItemPickupResult_2eproto::InitDefaults();
  return *internal_default_instance();
}

ItemPickupResult* ItemPickupResult::New(::google::protobuf::Arena* arena) const {
  ItemPickupResult* n = new ItemPickupResult;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ItemPickupResult::Clear() {
// @@protoc_insertion_point(message_clear_start:ItemPickupResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&status_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&remaining_time_) -
      reinterpret_cast<char*>(&status_)) + sizeof(remaining_time_));
  _internal_metadata_.Clear();
}

bool ItemPickupResult::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::NewPermanentCallback(&_internal_metadata_,
          &::google::protobuf::internal::InternalMetadataWithArenaLite::
              mutable_unknown_fields));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:ItemPickupResult)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 status = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &status_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 item = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &item_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 remaining_time = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &remaining_time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ItemPickupResult)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ItemPickupResult)
  return false;
#undef DO_
}

void ItemPickupResult::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ItemPickupResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 status = 1;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->status(), output);
  }

  // uint32 item = 2;
  if (this->item() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->item(), output);
  }

  // int32 remaining_time = 3;
  if (this->remaining_time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->remaining_time(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:ItemPickupResult)
}

size_t ItemPickupResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ItemPickupResult)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // int32 status = 1;
  if (this->status() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->status());
  }

  // uint32 item = 2;
  if (this->item() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->item());
  }

  // int32 remaining_time = 3;
  if (this->remaining_time() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->remaining_time());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ItemPickupResult::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ItemPickupResult*>(&from));
}

void ItemPickupResult::MergeFrom(const ItemPickupResult& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ItemPickupResult)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.status() != 0) {
    set_status(from.status());
  }
  if (from.item() != 0) {
    set_item(from.item());
  }
  if (from.remaining_time() != 0) {
    set_remaining_time(from.remaining_time());
  }
}

void ItemPickupResult::CopyFrom(const ItemPickupResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ItemPickupResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ItemPickupResult::IsInitialized() const {
  return true;
}

void ItemPickupResult::Swap(ItemPickupResult* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ItemPickupResult::InternalSwap(ItemPickupResult* other) {
  using std::swap;
  swap(status_, other->status_);
  swap(item_, other->item_);
  swap(remaining_time_, other->remaining_time_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string ItemPickupResult::GetTypeName() const {
  return "ItemPickupResult";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ItemPickupResult

// int32 status = 1;
void ItemPickupResult::clear_status() {
  status_ = 0;
}
::google::protobuf::int32 ItemPickupResult::status() const {
  // @@protoc_insertion_point(field_get:ItemPickupResult.status)
  return status_;
}
void ItemPickupResult::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:ItemPickupResult.status)
}

// uint32 item = 2;
void ItemPickupResult::clear_item() {
  item_ = 0u;
}
::google::protobuf::uint32 ItemPickupResult::item() const {
  // @@protoc_insertion_point(field_get:ItemPickupResult.item)
  return item_;
}
void ItemPickupResult::set_item(::google::protobuf::uint32 value) {
  
  item_ = value;
  // @@protoc_insertion_point(field_set:ItemPickupResult.item)
}

// int32 remaining_time = 3;
void ItemPickupResult::clear_remaining_time() {
  remaining_time_ = 0;
}
::google::protobuf::int32 ItemPickupResult::remaining_time() const {
  // @@protoc_insertion_point(field_get:ItemPickupResult.remaining_time)
  return remaining_time_;
}
void ItemPickupResult::set_remaining_time(::google::protobuf::int32 value) {
  
  remaining_time_ = value;
  // @@protoc_insertion_point(field_set:ItemPickupResult.remaining_time)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
