// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemApplicationUpdate.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ItemApplicationUpdate.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
class ItemApplicationInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ItemApplicationInfo>
     _instance;
} _ItemApplicationInfo_default_instance_;
class ItemApplicationUpdateDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ItemApplicationUpdate>
     _instance;
} _ItemApplicationUpdate_default_instance_;
class ItemApplicationUpdateAllDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ItemApplicationUpdateAll>
     _instance;
} _ItemApplicationUpdateAll_default_instance_;

namespace protobuf_ItemApplicationUpdate_2eproto {

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _ItemApplicationInfo_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_ItemApplicationInfo_default_instance_);_ItemApplicationUpdate_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_ItemApplicationUpdate_default_instance_);_ItemApplicationUpdateAll_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_ItemApplicationUpdateAll_default_instance_);_ItemApplicationUpdate_default_instance_._instance.get_mutable()->app_ = const_cast< ::ItemApplicationInfo*>(
      ::ItemApplicationInfo::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}

}  // namespace protobuf_ItemApplicationUpdate_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ItemApplicationInfo::kApplyFieldNumber;
const int ItemApplicationInfo::kItemIdFieldNumber;
const int ItemApplicationInfo::kDurationFieldNumber;
const int ItemApplicationInfo::kRemainingTimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ItemApplicationInfo::ItemApplicationInfo()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_ItemApplicationUpdate_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ItemApplicationInfo)
}
ItemApplicationInfo::ItemApplicationInfo(const ItemApplicationInfo& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&apply_, &from.apply_,
    static_cast<size_t>(reinterpret_cast<char*>(&remaining_time_) -
    reinterpret_cast<char*>(&apply_)) + sizeof(remaining_time_));
  // @@protoc_insertion_point(copy_constructor:ItemApplicationInfo)
}

void ItemApplicationInfo::SharedCtor() {
  ::memset(&apply_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&remaining_time_) -
      reinterpret_cast<char*>(&apply_)) + sizeof(remaining_time_));
  _cached_size_ = 0;
}

ItemApplicationInfo::~ItemApplicationInfo() {
  // @@protoc_insertion_point(destructor:ItemApplicationInfo)
  SharedDtor();
}

void ItemApplicationInfo::SharedDtor() {
}

void ItemApplicationInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ItemApplicationInfo& ItemApplicationInfo::default_instance() {
  protobuf_ItemApplicationUpdate_2eproto::InitDefaults();
  return *internal_default_instance();
}

ItemApplicationInfo* ItemApplicationInfo::New(::google::protobuf::Arena* arena) const {
  ItemApplicationInfo* n = new ItemApplicationInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ItemApplicationInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:ItemApplicationInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&apply_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&remaining_time_) -
      reinterpret_cast<char*>(&apply_)) + sizeof(remaining_time_));
  _internal_metadata_.Clear();
}

bool ItemApplicationInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::NewPermanentCallback(&_internal_metadata_,
          &::google::protobuf::internal::InternalMetadataWithArenaLite::
              mutable_unknown_fields));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:ItemApplicationInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool apply = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &apply_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 item_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &item_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 duration = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &duration_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 remaining_time = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &remaining_time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ItemApplicationInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ItemApplicationInfo)
  return false;
#undef DO_
}

void ItemApplicationInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ItemApplicationInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool apply = 1;
  if (this->apply() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->apply(), output);
  }

  // uint32 item_id = 2;
  if (this->item_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->item_id(), output);
  }

  // int32 duration = 3;
  if (this->duration() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->duration(), output);
  }

  // int32 remaining_time = 4;
  if (this->remaining_time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->remaining_time(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:ItemApplicationInfo)
}

size_t ItemApplicationInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ItemApplicationInfo)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // bool apply = 1;
  if (this->apply() != 0) {
    total_size += 1 + 1;
  }

  // uint32 item_id = 2;
  if (this->item_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->item_id());
  }

  // int32 duration = 3;
  if (this->duration() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->duration());
  }

  // int32 remaining_time = 4;
  if (this->remaining_time() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->remaining_time());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ItemApplicationInfo::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ItemApplicationInfo*>(&from));
}

void ItemApplicationInfo::MergeFrom(const ItemApplicationInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ItemApplicationInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.apply() != 0) {
    set_apply(from.apply());
  }
  if (from.item_id() != 0) {
    set_item_id(from.item_id());
  }
  if (from.duration() != 0) {
    set_duration(from.duration());
  }
  if (from.remaining_time() != 0) {
    set_remaining_time(from.remaining_time());
  }
}

void ItemApplicationInfo::CopyFrom(const ItemApplicationInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ItemApplicationInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ItemApplicationInfo::IsInitialized() const {
  return true;
}

void ItemApplicationInfo::Swap(ItemApplicationInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ItemApplicationInfo::InternalSwap(ItemApplicationInfo* other) {
  using std::swap;
  swap(apply_, other->apply_);
  swap(item_id_, other->item_id_);
  swap(duration_, other->duration_);
  swap(remaining_time_, other->remaining_time_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string ItemApplicationInfo::GetTypeName() const {
  return "ItemApplicationInfo";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ItemApplicationInfo

// bool apply = 1;
void ItemApplicationInfo::clear_apply() {
  apply_ = false;
}
bool ItemApplicationInfo::apply() const {
  // @@protoc_insertion_point(field_get:ItemApplicationInfo.apply)
  return apply_;
}
void ItemApplicationInfo::set_apply(bool value) {
  
  apply_ = value;
  // @@protoc_insertion_point(field_set:ItemApplicationInfo.apply)
}

// uint32 item_id = 2;
void ItemApplicationInfo::clear_item_id() {
  item_id_ = 0u;
}
::google::protobuf::uint32 ItemApplicationInfo::item_id() const {
  // @@protoc_insertion_point(field_get:ItemApplicationInfo.item_id)
  return item_id_;
}
void ItemApplicationInfo::set_item_id(::google::protobuf::uint32 value) {
  
  item_id_ = value;
  // @@protoc_insertion_point(field_set:ItemApplicationInfo.item_id)
}

// int32 duration = 3;
void ItemApplicationInfo::clear_duration() {
  duration_ = 0;
}
::google::protobuf::int32 ItemApplicationInfo::duration() const {
  // @@protoc_insertion_point(field_get:ItemApplicationInfo.duration)
  return duration_;
}
void ItemApplicationInfo::set_duration(::google::protobuf::int32 value) {
  
  duration_ = value;
  // @@protoc_insertion_point(field_set:ItemApplicationInfo.duration)
}

// int32 remaining_time = 4;
void ItemApplicationInfo::clear_remaining_time() {
  remaining_time_ = 0;
}
::google::protobuf::int32 ItemApplicationInfo::remaining_time() const {
  // @@protoc_insertion_point(field_get:ItemApplicationInfo.remaining_time)
  return remaining_time_;
}
void ItemApplicationInfo::set_remaining_time(::google::protobuf::int32 value) {
  
  remaining_time_ = value;
  // @@protoc_insertion_point(field_set:ItemApplicationInfo.remaining_time)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ItemApplicationUpdate::kTargetFieldNumber;
const int ItemApplicationUpdate::kAppFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ItemApplicationUpdate::ItemApplicationUpdate()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_ItemApplicationUpdate_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ItemApplicationUpdate)
}
ItemApplicationUpdate::ItemApplicationUpdate(const ItemApplicationUpdate& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_app()) {
    app_ = new ::ItemApplicationInfo(*from.app_);
  } else {
    app_ = NULL;
  }
  target_ = from.target_;
  // @@protoc_insertion_point(copy_constructor:ItemApplicationUpdate)
}

void ItemApplicationUpdate::SharedCtor() {
  ::memset(&app_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&target_) -
      reinterpret_cast<char*>(&app_)) + sizeof(target_));
  _cached_size_ = 0;
}

ItemApplicationUpdate::~ItemApplicationUpdate() {
  // @@protoc_insertion_point(destructor:ItemApplicationUpdate)
  SharedDtor();
}

void ItemApplicationUpdate::SharedDtor() {
  if (this != internal_default_instance()) delete app_;
}

void ItemApplicationUpdate::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ItemApplicationUpdate& ItemApplicationUpdate::default_instance() {
  protobuf_ItemApplicationUpdate_2eproto::InitDefaults();
  return *internal_default_instance();
}

ItemApplicationUpdate* ItemApplicationUpdate::New(::google::protobuf::Arena* arena) const {
  ItemApplicationUpdate* n = new ItemApplicationUpdate;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ItemApplicationUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:ItemApplicationUpdate)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && app_ != NULL) {
    delete app_;
  }
  app_ = NULL;
  target_ = 0u;
  _internal_metadata_.Clear();
}

bool ItemApplicationUpdate::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::NewPermanentCallback(&_internal_metadata_,
          &::google::protobuf::internal::InternalMetadataWithArenaLite::
              mutable_unknown_fields));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:ItemApplicationUpdate)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 target = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &target_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .ItemApplicationInfo app = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_app()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ItemApplicationUpdate)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ItemApplicationUpdate)
  return false;
#undef DO_
}

void ItemApplicationUpdate::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ItemApplicationUpdate)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 target = 1;
  if (this->target() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->target(), output);
  }

  // .ItemApplicationInfo app = 2;
  if (this->has_app()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, *this->app_, output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:ItemApplicationUpdate)
}

size_t ItemApplicationUpdate::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ItemApplicationUpdate)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // .ItemApplicationInfo app = 2;
  if (this->has_app()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->app_);
  }

  // uint32 target = 1;
  if (this->target() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->target());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ItemApplicationUpdate::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ItemApplicationUpdate*>(&from));
}

void ItemApplicationUpdate::MergeFrom(const ItemApplicationUpdate& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ItemApplicationUpdate)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_app()) {
    mutable_app()->::ItemApplicationInfo::MergeFrom(from.app());
  }
  if (from.target() != 0) {
    set_target(from.target());
  }
}

void ItemApplicationUpdate::CopyFrom(const ItemApplicationUpdate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ItemApplicationUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ItemApplicationUpdate::IsInitialized() const {
  return true;
}

void ItemApplicationUpdate::Swap(ItemApplicationUpdate* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ItemApplicationUpdate::InternalSwap(ItemApplicationUpdate* other) {
  using std::swap;
  swap(app_, other->app_);
  swap(target_, other->target_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string ItemApplicationUpdate::GetTypeName() const {
  return "ItemApplicationUpdate";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ItemApplicationUpdate

// uint32 target = 1;
void ItemApplicationUpdate::clear_target() {
  target_ = 0u;
}
::google::protobuf::uint32 ItemApplicationUpdate::target() const {
  // @@protoc_insertion_point(field_get:ItemApplicationUpdate.target)
  return target_;
}
void ItemApplicationUpdate::set_target(::google::protobuf::uint32 value) {
  
  target_ = value;
  // @@protoc_insertion_point(field_set:ItemApplicationUpdate.target)
}

// .ItemApplicationInfo app = 2;
bool ItemApplicationUpdate::has_app() const {
  return this != internal_default_instance() && app_ != NULL;
}
void ItemApplicationUpdate::clear_app() {
  if (GetArenaNoVirtual() == NULL && app_ != NULL) delete app_;
  app_ = NULL;
}
const ::ItemApplicationInfo& ItemApplicationUpdate::app() const {
  const ::ItemApplicationInfo* p = app_;
  // @@protoc_insertion_point(field_get:ItemApplicationUpdate.app)
  return p != NULL ? *p : *reinterpret_cast<const ::ItemApplicationInfo*>(
      &::_ItemApplicationInfo_default_instance_);
}
::ItemApplicationInfo* ItemApplicationUpdate::mutable_app() {
  
  if (app_ == NULL) {
    app_ = new ::ItemApplicationInfo;
  }
  // @@protoc_insertion_point(field_mutable:ItemApplicationUpdate.app)
  return app_;
}
::ItemApplicationInfo* ItemApplicationUpdate::release_app() {
  // @@protoc_insertion_point(field_release:ItemApplicationUpdate.app)
  
  ::ItemApplicationInfo* temp = app_;
  app_ = NULL;
  return temp;
}
void ItemApplicationUpdate::set_allocated_app(::ItemApplicationInfo* app) {
  delete app_;
  app_ = app;
  if (app) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:ItemApplicationUpdate.app)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ItemApplicationUpdateAll::kTargetFieldNumber;
const int ItemApplicationUpdateAll::kAppListFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ItemApplicationUpdateAll::ItemApplicationUpdateAll()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_ItemApplicationUpdate_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ItemApplicationUpdateAll)
}
ItemApplicationUpdateAll::ItemApplicationUpdateAll(const ItemApplicationUpdateAll& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      app_list_(from.app_list_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  target_ = from.target_;
  // @@protoc_insertion_point(copy_constructor:ItemApplicationUpdateAll)
}

void ItemApplicationUpdateAll::SharedCtor() {
  target_ = 0u;
  _cached_size_ = 0;
}

ItemApplicationUpdateAll::~ItemApplicationUpdateAll() {
  // @@protoc_insertion_point(destructor:ItemApplicationUpdateAll)
  SharedDtor();
}

void ItemApplicationUpdateAll::SharedDtor() {
}

void ItemApplicationUpdateAll::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ItemApplicationUpdateAll& ItemApplicationUpdateAll::default_instance() {
  protobuf_ItemApplicationUpdate_2eproto::InitDefaults();
  return *internal_default_instance();
}

ItemApplicationUpdateAll* ItemApplicationUpdateAll::New(::google::protobuf::Arena* arena) const {
  ItemApplicationUpdateAll* n = new ItemApplicationUpdateAll;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ItemApplicationUpdateAll::Clear() {
// @@protoc_insertion_point(message_clear_start:ItemApplicationUpdateAll)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  app_list_.Clear();
  target_ = 0u;
  _internal_metadata_.Clear();
}

bool ItemApplicationUpdateAll::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::NewPermanentCallback(&_internal_metadata_,
          &::google::protobuf::internal::InternalMetadataWithArenaLite::
              mutable_unknown_fields));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:ItemApplicationUpdateAll)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 target = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &target_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .ItemApplicationInfo app_list = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_app_list()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ItemApplicationUpdateAll)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ItemApplicationUpdateAll)
  return false;
#undef DO_
}

void ItemApplicationUpdateAll::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ItemApplicationUpdateAll)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 target = 1;
  if (this->target() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->target(), output);
  }

  // repeated .ItemApplicationInfo app_list = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->app_list_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, this->app_list(static_cast<int>(i)), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:ItemApplicationUpdateAll)
}

size_t ItemApplicationUpdateAll::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ItemApplicationUpdateAll)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // repeated .ItemApplicationInfo app_list = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->app_list_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->app_list(static_cast<int>(i)));
    }
  }

  // uint32 target = 1;
  if (this->target() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->target());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ItemApplicationUpdateAll::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ItemApplicationUpdateAll*>(&from));
}

void ItemApplicationUpdateAll::MergeFrom(const ItemApplicationUpdateAll& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ItemApplicationUpdateAll)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  app_list_.MergeFrom(from.app_list_);
  if (from.target() != 0) {
    set_target(from.target());
  }
}

void ItemApplicationUpdateAll::CopyFrom(const ItemApplicationUpdateAll& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ItemApplicationUpdateAll)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ItemApplicationUpdateAll::IsInitialized() const {
  return true;
}

void ItemApplicationUpdateAll::Swap(ItemApplicationUpdateAll* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ItemApplicationUpdateAll::InternalSwap(ItemApplicationUpdateAll* other) {
  using std::swap;
  app_list_.InternalSwap(&other->app_list_);
  swap(target_, other->target_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string ItemApplicationUpdateAll::GetTypeName() const {
  return "ItemApplicationUpdateAll";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ItemApplicationUpdateAll

// uint32 target = 1;
void ItemApplicationUpdateAll::clear_target() {
  target_ = 0u;
}
::google::protobuf::uint32 ItemApplicationUpdateAll::target() const {
  // @@protoc_insertion_point(field_get:ItemApplicationUpdateAll.target)
  return target_;
}
void ItemApplicationUpdateAll::set_target(::google::protobuf::uint32 value) {
  
  target_ = value;
  // @@protoc_insertion_point(field_set:ItemApplicationUpdateAll.target)
}

// repeated .ItemApplicationInfo app_list = 2;
int ItemApplicationUpdateAll::app_list_size() const {
  return app_list_.size();
}
void ItemApplicationUpdateAll::clear_app_list() {
  app_list_.Clear();
}
const ::ItemApplicationInfo& ItemApplicationUpdateAll::app_list(int index) const {
  // @@protoc_insertion_point(field_get:ItemApplicationUpdateAll.app_list)
  return app_list_.Get(index);
}
::ItemApplicationInfo* ItemApplicationUpdateAll::mutable_app_list(int index) {
  // @@protoc_insertion_point(field_mutable:ItemApplicationUpdateAll.app_list)
  return app_list_.Mutable(index);
}
::ItemApplicationInfo* ItemApplicationUpdateAll::add_app_list() {
  // @@protoc_insertion_point(field_add:ItemApplicationUpdateAll.app_list)
  return app_list_.Add();
}
::google::protobuf::RepeatedPtrField< ::ItemApplicationInfo >*
ItemApplicationUpdateAll::mutable_app_list() {
  // @@protoc_insertion_point(field_mutable_list:ItemApplicationUpdateAll.app_list)
  return &app_list_;
}
const ::google::protobuf::RepeatedPtrField< ::ItemApplicationInfo >&
ItemApplicationUpdateAll::app_list() const {
  // @@protoc_insertion_point(field_list:ItemApplicationUpdateAll.app_list)
  return app_list_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
