// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemPickupResult.proto

#ifndef PROTOBUF_ItemPickupResult_2eproto__INCLUDED
#define PROTOBUF_ItemPickupResult_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
class ItemPickupResult;
class ItemPickupResultDefaultTypeInternal;
extern ItemPickupResultDefaultTypeInternal _ItemPickupResult_default_instance_;

namespace protobuf_ItemPickupResult_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_ItemPickupResult_2eproto

// ===================================================================

class ItemPickupResult : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:ItemPickupResult) */ {
 public:
  ItemPickupResult();
  virtual ~ItemPickupResult();

  ItemPickupResult(const ItemPickupResult& from);

  inline ItemPickupResult& operator=(const ItemPickupResult& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ItemPickupResult(ItemPickupResult&& from) noexcept
    : ItemPickupResult() {
    *this = ::std::move(from);
  }

  inline ItemPickupResult& operator=(ItemPickupResult&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ItemPickupResult& default_instance();

  static inline const ItemPickupResult* internal_default_instance() {
    return reinterpret_cast<const ItemPickupResult*>(
               &_ItemPickupResult_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ItemPickupResult* other);
  friend void swap(ItemPickupResult& a, ItemPickupResult& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ItemPickupResult* New() const PROTOBUF_FINAL { return New(NULL); }

  ItemPickupResult* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const ItemPickupResult& from);
  void MergeFrom(const ItemPickupResult& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ItemPickupResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 status = 1;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // uint32 item = 2;
  void clear_item();
  static const int kItemFieldNumber = 2;
  ::google::protobuf::uint32 item() const;
  void set_item(::google::protobuf::uint32 value);

  // int32 remaining_time = 3;
  void clear_remaining_time();
  static const int kRemainingTimeFieldNumber = 3;
  ::google::protobuf::int32 remaining_time() const;
  void set_remaining_time(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ItemPickupResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::int32 status_;
  ::google::protobuf::uint32 item_;
  ::google::protobuf::int32 remaining_time_;
  mutable int _cached_size_;
  friend struct protobuf_ItemPickupResult_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ItemPickupResult

// int32 status = 1;
inline void ItemPickupResult::clear_status() {
  status_ = 0;
}
inline ::google::protobuf::int32 ItemPickupResult::status() const {
  // @@protoc_insertion_point(field_get:ItemPickupResult.status)
  return status_;
}
inline void ItemPickupResult::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:ItemPickupResult.status)
}

// uint32 item = 2;
inline void ItemPickupResult::clear_item() {
  item_ = 0u;
}
inline ::google::protobuf::uint32 ItemPickupResult::item() const {
  // @@protoc_insertion_point(field_get:ItemPickupResult.item)
  return item_;
}
inline void ItemPickupResult::set_item(::google::protobuf::uint32 value) {
  
  item_ = value;
  // @@protoc_insertion_point(field_set:ItemPickupResult.item)
}

// int32 remaining_time = 3;
inline void ItemPickupResult::clear_remaining_time() {
  remaining_time_ = 0;
}
inline ::google::protobuf::int32 ItemPickupResult::remaining_time() const {
  // @@protoc_insertion_point(field_get:ItemPickupResult.remaining_time)
  return remaining_time_;
}
inline void ItemPickupResult::set_remaining_time(::google::protobuf::int32 value) {
  
  remaining_time_ = value;
  // @@protoc_insertion_point(field_set:ItemPickupResult.remaining_time)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ItemPickupResult_2eproto__INCLUDED
