// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QueryTheaterStatusList.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "QueryTheaterStatusList.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
class QueryTheaterStatusListDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<QueryTheaterStatusList>
     _instance;
} _QueryTheaterStatusList_default_instance_;

namespace protobuf_QueryTheaterStatusList_2eproto {

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _QueryTheaterStatusList_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_QueryTheaterStatusList_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}

}  // namespace protobuf_QueryTheaterStatusList_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

QueryTheaterStatusList::QueryTheaterStatusList()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_QueryTheaterStatusList_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:QueryTheaterStatusList)
}
QueryTheaterStatusList::QueryTheaterStatusList(const QueryTheaterStatusList& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:QueryTheaterStatusList)
}

void QueryTheaterStatusList::SharedCtor() {
  _cached_size_ = 0;
}

QueryTheaterStatusList::~QueryTheaterStatusList() {
  // @@protoc_insertion_point(destructor:QueryTheaterStatusList)
  SharedDtor();
}

void QueryTheaterStatusList::SharedDtor() {
}

void QueryTheaterStatusList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const QueryTheaterStatusList& QueryTheaterStatusList::default_instance() {
  protobuf_QueryTheaterStatusList_2eproto::InitDefaults();
  return *internal_default_instance();
}

QueryTheaterStatusList* QueryTheaterStatusList::New(::google::protobuf::Arena* arena) const {
  QueryTheaterStatusList* n = new QueryTheaterStatusList;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void QueryTheaterStatusList::Clear() {
// @@protoc_insertion_point(message_clear_start:QueryTheaterStatusList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool QueryTheaterStatusList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::NewPermanentCallback(&_internal_metadata_,
          &::google::protobuf::internal::InternalMetadataWithArenaLite::
              mutable_unknown_fields));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:QueryTheaterStatusList)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(
        input, tag, &unknown_fields_stream));
  }
success:
  // @@protoc_insertion_point(parse_success:QueryTheaterStatusList)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:QueryTheaterStatusList)
  return false;
#undef DO_
}

void QueryTheaterStatusList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:QueryTheaterStatusList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:QueryTheaterStatusList)
}

size_t QueryTheaterStatusList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:QueryTheaterStatusList)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void QueryTheaterStatusList::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const QueryTheaterStatusList*>(&from));
}

void QueryTheaterStatusList::MergeFrom(const QueryTheaterStatusList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:QueryTheaterStatusList)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void QueryTheaterStatusList::CopyFrom(const QueryTheaterStatusList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:QueryTheaterStatusList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool QueryTheaterStatusList::IsInitialized() const {
  return true;
}

void QueryTheaterStatusList::Swap(QueryTheaterStatusList* other) {
  if (other == this) return;
  InternalSwap(other);
}
void QueryTheaterStatusList::InternalSwap(QueryTheaterStatusList* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string QueryTheaterStatusList::GetTypeName() const {
  return "QueryTheaterStatusList";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// QueryTheaterStatusList

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
