// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TheaterInfo.proto

#ifndef PROTOBUF_TheaterInfo_2eproto__INCLUDED
#define PROTOBUF_TheaterInfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
class TheaterInfo;
class TheaterInfoDefaultTypeInternal;
extern TheaterInfoDefaultTypeInternal _TheaterInfo_default_instance_;

namespace protobuf_TheaterInfo_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_TheaterInfo_2eproto

// ===================================================================

class TheaterInfo : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:TheaterInfo) */ {
 public:
  TheaterInfo();
  virtual ~TheaterInfo();

  TheaterInfo(const TheaterInfo& from);

  inline TheaterInfo& operator=(const TheaterInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TheaterInfo(TheaterInfo&& from) noexcept
    : TheaterInfo() {
    *this = ::std::move(from);
  }

  inline TheaterInfo& operator=(TheaterInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const TheaterInfo& default_instance();

  static inline const TheaterInfo* internal_default_instance() {
    return reinterpret_cast<const TheaterInfo*>(
               &_TheaterInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(TheaterInfo* other);
  friend void swap(TheaterInfo& a, TheaterInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TheaterInfo* New() const PROTOBUF_FINAL { return New(NULL); }

  TheaterInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const TheaterInfo& from);
  void MergeFrom(const TheaterInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TheaterInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 theater_id = 1;
  void clear_theater_id();
  static const int kTheaterIdFieldNumber = 1;
  ::google::protobuf::uint32 theater_id() const;
  void set_theater_id(::google::protobuf::uint32 value);

  // uint32 map_id = 2;
  void clear_map_id();
  static const int kMapIdFieldNumber = 2;
  ::google::protobuf::uint32 map_id() const;
  void set_map_id(::google::protobuf::uint32 value);

  // uint32 combat_grade = 3;
  void clear_combat_grade();
  static const int kCombatGradeFieldNumber = 3;
  ::google::protobuf::uint32 combat_grade() const;
  void set_combat_grade(::google::protobuf::uint32 value);

  // int32 safezone_center_x = 5;
  void clear_safezone_center_x();
  static const int kSafezoneCenterXFieldNumber = 5;
  ::google::protobuf::int32 safezone_center_x() const;
  void set_safezone_center_x(::google::protobuf::int32 value);

  // int32 safezone_center_y = 6;
  void clear_safezone_center_y();
  static const int kSafezoneCenterYFieldNumber = 6;
  ::google::protobuf::int32 safezone_center_y() const;
  void set_safezone_center_y(::google::protobuf::int32 value);

  // bool request_battle_end_ad = 4;
  void clear_request_battle_end_ad();
  static const int kRequestBattleEndAdFieldNumber = 4;
  bool request_battle_end_ad() const;
  void set_request_battle_end_ad(bool value);

  // bool enable_app_review_mode = 9;
  void clear_enable_app_review_mode();
  static const int kEnableAppReviewModeFieldNumber = 9;
  bool enable_app_review_mode() const;
  void set_enable_app_review_mode(bool value);

  // int32 safezone_radius = 7;
  void clear_safezone_radius();
  static const int kSafezoneRadiusFieldNumber = 7;
  ::google::protobuf::int32 safezone_radius() const;
  void set_safezone_radius(::google::protobuf::int32 value);

  // int32 battle_duration = 8;
  void clear_battle_duration();
  static const int kBattleDurationFieldNumber = 8;
  ::google::protobuf::int32 battle_duration() const;
  void set_battle_duration(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:TheaterInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::uint32 theater_id_;
  ::google::protobuf::uint32 map_id_;
  ::google::protobuf::uint32 combat_grade_;
  ::google::protobuf::int32 safezone_center_x_;
  ::google::protobuf::int32 safezone_center_y_;
  bool request_battle_end_ad_;
  bool enable_app_review_mode_;
  ::google::protobuf::int32 safezone_radius_;
  ::google::protobuf::int32 battle_duration_;
  mutable int _cached_size_;
  friend struct protobuf_TheaterInfo_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TheaterInfo

// uint32 theater_id = 1;
inline void TheaterInfo::clear_theater_id() {
  theater_id_ = 0u;
}
inline ::google::protobuf::uint32 TheaterInfo::theater_id() const {
  // @@protoc_insertion_point(field_get:TheaterInfo.theater_id)
  return theater_id_;
}
inline void TheaterInfo::set_theater_id(::google::protobuf::uint32 value) {
  
  theater_id_ = value;
  // @@protoc_insertion_point(field_set:TheaterInfo.theater_id)
}

// uint32 map_id = 2;
inline void TheaterInfo::clear_map_id() {
  map_id_ = 0u;
}
inline ::google::protobuf::uint32 TheaterInfo::map_id() const {
  // @@protoc_insertion_point(field_get:TheaterInfo.map_id)
  return map_id_;
}
inline void TheaterInfo::set_map_id(::google::protobuf::uint32 value) {
  
  map_id_ = value;
  // @@protoc_insertion_point(field_set:TheaterInfo.map_id)
}

// uint32 combat_grade = 3;
inline void TheaterInfo::clear_combat_grade() {
  combat_grade_ = 0u;
}
inline ::google::protobuf::uint32 TheaterInfo::combat_grade() const {
  // @@protoc_insertion_point(field_get:TheaterInfo.combat_grade)
  return combat_grade_;
}
inline void TheaterInfo::set_combat_grade(::google::protobuf::uint32 value) {
  
  combat_grade_ = value;
  // @@protoc_insertion_point(field_set:TheaterInfo.combat_grade)
}

// bool request_battle_end_ad = 4;
inline void TheaterInfo::clear_request_battle_end_ad() {
  request_battle_end_ad_ = false;
}
inline bool TheaterInfo::request_battle_end_ad() const {
  // @@protoc_insertion_point(field_get:TheaterInfo.request_battle_end_ad)
  return request_battle_end_ad_;
}
inline void TheaterInfo::set_request_battle_end_ad(bool value) {
  
  request_battle_end_ad_ = value;
  // @@protoc_insertion_point(field_set:TheaterInfo.request_battle_end_ad)
}

// int32 safezone_center_x = 5;
inline void TheaterInfo::clear_safezone_center_x() {
  safezone_center_x_ = 0;
}
inline ::google::protobuf::int32 TheaterInfo::safezone_center_x() const {
  // @@protoc_insertion_point(field_get:TheaterInfo.safezone_center_x)
  return safezone_center_x_;
}
inline void TheaterInfo::set_safezone_center_x(::google::protobuf::int32 value) {
  
  safezone_center_x_ = value;
  // @@protoc_insertion_point(field_set:TheaterInfo.safezone_center_x)
}

// int32 safezone_center_y = 6;
inline void TheaterInfo::clear_safezone_center_y() {
  safezone_center_y_ = 0;
}
inline ::google::protobuf::int32 TheaterInfo::safezone_center_y() const {
  // @@protoc_insertion_point(field_get:TheaterInfo.safezone_center_y)
  return safezone_center_y_;
}
inline void TheaterInfo::set_safezone_center_y(::google::protobuf::int32 value) {
  
  safezone_center_y_ = value;
  // @@protoc_insertion_point(field_set:TheaterInfo.safezone_center_y)
}

// int32 safezone_radius = 7;
inline void TheaterInfo::clear_safezone_radius() {
  safezone_radius_ = 0;
}
inline ::google::protobuf::int32 TheaterInfo::safezone_radius() const {
  // @@protoc_insertion_point(field_get:TheaterInfo.safezone_radius)
  return safezone_radius_;
}
inline void TheaterInfo::set_safezone_radius(::google::protobuf::int32 value) {
  
  safezone_radius_ = value;
  // @@protoc_insertion_point(field_set:TheaterInfo.safezone_radius)
}

// int32 battle_duration = 8;
inline void TheaterInfo::clear_battle_duration() {
  battle_duration_ = 0;
}
inline ::google::protobuf::int32 TheaterInfo::battle_duration() const {
  // @@protoc_insertion_point(field_get:TheaterInfo.battle_duration)
  return battle_duration_;
}
inline void TheaterInfo::set_battle_duration(::google::protobuf::int32 value) {
  
  battle_duration_ = value;
  // @@protoc_insertion_point(field_set:TheaterInfo.battle_duration)
}

// bool enable_app_review_mode = 9;
inline void TheaterInfo::clear_enable_app_review_mode() {
  enable_app_review_mode_ = false;
}
inline bool TheaterInfo::enable_app_review_mode() const {
  // @@protoc_insertion_point(field_get:TheaterInfo.enable_app_review_mode)
  return enable_app_review_mode_;
}
inline void TheaterInfo::set_enable_app_review_mode(bool value) {
  
  enable_app_review_mode_ = value;
  // @@protoc_insertion_point(field_set:TheaterInfo.enable_app_review_mode)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_TheaterInfo_2eproto__INCLUDED
