// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorldStatus.proto

#ifndef PROTOBUF_WorldStatus_2eproto__INCLUDED
#define PROTOBUF_WorldStatus_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
class WorldStatus;
class WorldStatusDefaultTypeInternal;
extern WorldStatusDefaultTypeInternal _WorldStatus_default_instance_;

namespace protobuf_WorldStatus_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_WorldStatus_2eproto

// ===================================================================

class WorldStatus : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:WorldStatus) */ {
 public:
  WorldStatus();
  virtual ~WorldStatus();

  WorldStatus(const WorldStatus& from);

  inline WorldStatus& operator=(const WorldStatus& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  WorldStatus(WorldStatus&& from) noexcept
    : WorldStatus() {
    *this = ::std::move(from);
  }

  inline WorldStatus& operator=(WorldStatus&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const WorldStatus& default_instance();

  static inline const WorldStatus* internal_default_instance() {
    return reinterpret_cast<const WorldStatus*>(
               &_WorldStatus_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(WorldStatus* other);
  friend void swap(WorldStatus& a, WorldStatus& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WorldStatus* New() const PROTOBUF_FINAL { return New(NULL); }

  WorldStatus* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const WorldStatus& from);
  void MergeFrom(const WorldStatus& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(WorldStatus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 max_players = 1;
  void clear_max_players();
  static const int kMaxPlayersFieldNumber = 1;
  ::google::protobuf::int32 max_players() const;
  void set_max_players(::google::protobuf::int32 value);

  // int32 online_players = 2;
  void clear_online_players();
  static const int kOnlinePlayersFieldNumber = 2;
  ::google::protobuf::int32 online_players() const;
  void set_online_players(::google::protobuf::int32 value);

  // int32 update_diff = 3;
  void clear_update_diff();
  static const int kUpdateDiffFieldNumber = 3;
  ::google::protobuf::int32 update_diff() const;
  void set_update_diff(::google::protobuf::int32 value);

  // int32 theater_count = 4;
  void clear_theater_count();
  static const int kTheaterCountFieldNumber = 4;
  ::google::protobuf::int32 theater_count() const;
  void set_theater_count(::google::protobuf::int32 value);

  // int32 queued_players = 5;
  void clear_queued_players();
  static const int kQueuedPlayersFieldNumber = 5;
  ::google::protobuf::int32 queued_players() const;
  void set_queued_players(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:WorldStatus)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::int32 max_players_;
  ::google::protobuf::int32 online_players_;
  ::google::protobuf::int32 update_diff_;
  ::google::protobuf::int32 theater_count_;
  ::google::protobuf::int32 queued_players_;
  mutable int _cached_size_;
  friend struct protobuf_WorldStatus_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// WorldStatus

// int32 max_players = 1;
inline void WorldStatus::clear_max_players() {
  max_players_ = 0;
}
inline ::google::protobuf::int32 WorldStatus::max_players() const {
  // @@protoc_insertion_point(field_get:WorldStatus.max_players)
  return max_players_;
}
inline void WorldStatus::set_max_players(::google::protobuf::int32 value) {
  
  max_players_ = value;
  // @@protoc_insertion_point(field_set:WorldStatus.max_players)
}

// int32 online_players = 2;
inline void WorldStatus::clear_online_players() {
  online_players_ = 0;
}
inline ::google::protobuf::int32 WorldStatus::online_players() const {
  // @@protoc_insertion_point(field_get:WorldStatus.online_players)
  return online_players_;
}
inline void WorldStatus::set_online_players(::google::protobuf::int32 value) {
  
  online_players_ = value;
  // @@protoc_insertion_point(field_set:WorldStatus.online_players)
}

// int32 update_diff = 3;
inline void WorldStatus::clear_update_diff() {
  update_diff_ = 0;
}
inline ::google::protobuf::int32 WorldStatus::update_diff() const {
  // @@protoc_insertion_point(field_get:WorldStatus.update_diff)
  return update_diff_;
}
inline void WorldStatus::set_update_diff(::google::protobuf::int32 value) {
  
  update_diff_ = value;
  // @@protoc_insertion_point(field_set:WorldStatus.update_diff)
}

// int32 theater_count = 4;
inline void WorldStatus::clear_theater_count() {
  theater_count_ = 0;
}
inline ::google::protobuf::int32 WorldStatus::theater_count() const {
  // @@protoc_insertion_point(field_get:WorldStatus.theater_count)
  return theater_count_;
}
inline void WorldStatus::set_theater_count(::google::protobuf::int32 value) {
  
  theater_count_ = value;
  // @@protoc_insertion_point(field_set:WorldStatus.theater_count)
}

// int32 queued_players = 5;
inline void WorldStatus::clear_queued_players() {
  queued_players_ = 0;
}
inline ::google::protobuf::int32 WorldStatus::queued_players() const {
  // @@protoc_insertion_point(field_get:WorldStatus.queued_players)
  return queued_players_;
}
inline void WorldStatus::set_queued_players(::google::protobuf::int32 value) {
  
  queued_players_ = value;
  // @@protoc_insertion_point(field_set:WorldStatus.queued_players)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_WorldStatus_2eproto__INCLUDED
