#ifndef __UPDATE_FIELDS_H__
#define __UPDATE_FIELDS_H__

#include "game/entities/UnitSlotDefines.h"

enum SUnitField
{
	SUNIT_FIELD_HEALTH					= 0,	// UpdateType: VALUES|CREATE
	SUNIT_FIELD_MAX_HEALTH,						// UpdateType: VALUES|CREATE
	SUNIT_FIELD_MOVEMENT_INFO,					// UpdateType: CREATE
	SUNIT_FIELD_STAMINA_INFO,					// UpdateType: CREATE
	SUNIT_FIELD_MOVE_SPEED,						// UpdateType: VALUES|CREATE
	SUNIT_FIELD_ATTACK_RANGE,					// UpdateType: VALUES|CREATE
	SUNIT_FIELD_ATTACK_TAKES_STAMINA,			// UpdateType: CREATE
	SUNIT_FIELD_DISPLAYID,						// UpdateType: CREATE
	SUNIT_FIELD_LEVEL,							// UpdateType: VALUES|CREATE
	SUNIT_FIELD_SMILEY,							// UpdateType: VALUES|CREATE
	SUNIT_FIELD_UNIT_FLAGS,						// UpdateType: VALUES|CREATE
	SUNIT_FIELD_MAGIC_BEAN_COUNT,				// UpdateType: VALUES|CREATE
	SUNIT_END,
};

enum SPlayerField
{
	SPLAYER_FIELD_IS_GM					= SUNIT_END,		// UpdateType: VALUES|CREATE
	SPLAYER_FIELD_KILL_COUNT,								// UpdateType: VALUES|CREATE
	SPLAYER_FIELD_EXPERIENCE,								// UpdateType: VALUES|CREATE
	SPLAYER_FIELD_NEXTLEVEL_XP,								// UpdateType: VALUES|CREATE
	SPLAYER_FIELD_MONEY,									// UpdateType: VALUES|CREATE
	SPLAYER_FIELD_ITEM_HEAD,								// UpdateType: VALUES|CREATE
	SPLAYER_FIELD_ITEM_END				= SPLAYER_FIELD_ITEM_HEAD + UNIT_SLOTS_COUNT,
	SPLAYER_FIELD_CONCEALMENT_STATE		= SPLAYER_FIELD_ITEM_END,				// UpdateType: VALUES|CREATE 
	SPLAYER_FIELD_PICKUP_DURATION,							// UpdateType: CREATE
	SPLAYER_FIELD_PICKUP_TARGET,							// UpdateType: VALUES|CREATE
	SPLAYER_END,
};

enum SRobotField
{
	SROBOT_FIELD_TARGET					= SUNIT_END,	// UpdateType: VALUES|CREATE
	SROBOT_FIELD_AIACTION_TYPE,							// UpdateType: VALUES|CREATE
	SROBOT_FIELD_AIACTION_STATE,						// UpdateType: VALUES|CREATE
	SROBOT_END,
};

enum SItemBoxField
{
	SITEMBOX_FIELD_POSITION				= 0,	// UpdateType: CREATE
	SITEMBOX_FIELD_DIRECTION,					// UpdateType: CREATE
	SITEMBOX_FIELD_HEALTH,						// UpdateType: VALUES|CREATE
	SITEMBOX_FIELD_MAX_HEALTH,					// UpdateType: VALUES|CREATE
	SITEMBOX_END,
};

enum SItemField
{
	SITEM_FIELD_ITEMID					= 0,	// UpdateType: CREATE
    SITEM_FIELD_POSITION,						// UpdateType: CREATE
	SITEM_FIELD_COUNT,							// UpdateType: CREATE
	SITEM_FIELD_HOLDER,							// UpdateType: CREATE
	SITEM_FIELD_HOLDER_ORIGIN,					// UpdateType: CREATE
	SITEM_FIELD_LAUNCH_CENTER,					// UpdateType: CREATE
	SITEM_FIELD_LAUNCH_RADIUS_IN_MAP,			// UpdateType: CREATE
	SITEM_FIELD_DROP_DURATION,					// UpdateType: CREATE
	SITEM_FIELD_DROP_ELAPSED,					// UpdateType: CREATE
    SITEM_END, 
};

enum SCarriedItemField
{
	SCARRIEDITEM_FIELD_ITEMID			= 0,	// UpdateType: CREATE
	SCARRIEDITEM_FIELD_LEVEL,					// UpdateType: CREATE
	SCARRIEDITEM_FIELD_COUNT,					// UpdateType: VALUES|CREATE
	SCARRIEDITEM_FIELD_STACKABLE,				// UpdateType: CREATE
	SCARRIEDITEM_FIELD_COOLDOWN_DURATION,		// UpdateType: CREATE
	SCARRIEDITEM_END,
};

enum SProjectileField
{
	SPROJECTILE_FIELD_LAUNCHER			= 0,	// UpdateType: CREATE
	SPROJECTILE_FIELD_LAUNCHER_ORIGIN,			// UpdateType: CREATE
	SPROJECTILE_FIELD_ATTACK_RANGE,				// UpdateType: CREATE
	SPROJECTILE_FIELD_LAUNCH_CENTER,			// UpdateType: CREATE
	SPROJECTILE_FIELD_LAUNCH_RADIUS_IN_MAP,		// UpdateType: CREATE
	SPROJECTILE_FIELD_ORIENTATION,				// UpdateType: CREATE
	SPROJECTILE_FIELD_ELAPSED,					// UpdateType: CREATE
	SPROJECTILE_FIELD_DURATION,					// UpdateType: CREATE
	SPROJECTILE_FIELD_ATTACK_COUNTER,			// UpdateType: CREATE
	SPROJECTILE_FIELD_CONSUMED_STAMINA,			// UpdateType: CREATE
	SPROJECTILE_FIELD_SCALE,					// UpdateType: CREATE
	SPROJECTILE_FIELD_ATTACK_INFO_COUNTER,		// UpdateType: CREATE
	SPROJECTILE_FIELD_FLAG,						// UpdateType: CREATE
	SPROJECTILE_END,
};

enum SUnitLocatorField
{
	SUNIT_LOCATOR_FIELD_LOCATION		= 0,	// UpdateType: CREATE
	SUNIT_LOCATOR_FIELD_DISPLAYID,				// UpdateType: CREATE
	SUNIT_LOCATOR_FIELD_IS_ALIVE,				// UpdateType: VALUES|CREATE
	SUNIT_LOCATOR_FIELD_MOVE_SPEED,				// UpdateType: VALUES|CREATE
	SUNIT_LOCATOR_END,
};


#endif // __UPDATE_FIELDS_H__