#include "OpcodeHandler.h"

// #include "game/server/WorldSession.h"


// World Opcode Names
char const* gOpcodeNameTable[NUM_MSG_TYPES] = {
	"MSG_NULL",
	"SMSG_AUTH_CHALLENGE",
	"CMSG_AUTH_PROOF",
	"SMSG_AUTH_VERDICT",
	"CMSG_PLAYER_LOGIN",
	"CMSG_PLAYER_LOGOUT",
	"SMSG_THEATER_INFO",
	"CMSG_JOIN_THEATER",
	"SMSG_WAIT_FOR_PLAYERS",
	"SMSG_UPDATE_OBJECT",
	"SMSG_DESTROY_OBJECT",
	"CMSG_QUERY_CHARACTER_INFO",
	"SMSG_CHARACTER_INFO",
	"MSG_MOVE_START",
	"MSG_MOVE_SYNC",
	"MSG_MOVE_HEARTBEAT",
	"MSG_MOVE_TURN",
	"MSG_MOVE_STOP",
	"CMSG_ATTACK",
	"SMSG_LAUNCH_RESULT",
	"MSG_CHARGE_START",
	"MSG_CHARGE_STOP",
	"MSG_STAMINA_SYNC",
	"SMSG_MODIFY_STAMINA",
	"SMSG_DEATH_MESSAGE",
	"SMSG_TIME_SYNC_REQ",
	"CMSG_TIME_SYNC_RESP",
	"MSG_PING",
	"MSG_PONG",
	"CMSG_QUERY_WORLD_STATUS",
	"SMSG_WORLD_STATUS",
	"CMSG_QUERY_THEATER_STATUS_LIST",
	"SMSG_THEATER_STATUS_LIST",
	"CMSG_SMILEY_CHAT",
	"CMSG_QUERY_PLAYER_STATUS_LIST",
	"SMSG_PLAYER_STATUS_LIST",
	"CMSG_GM_COMMAND",
	"SMSG_TRANSPORT",
	"SMSG_FLASH_MESSAGE",
	"SMSG_PLAYER_ACTION_MESSAGE",
	"SMSG_REWARD_MESSAGE",
	"SMSG_BATTLE_UPDATE",
	"SMSG_BATTLE_RESULT",
	"SMSG_RELOCATE_LOCATOR",
	"SMSG_ITEM_PICKUP_RESULT",
	"CMSG_USE_ITEM",
	"SMSG_ITEM_USE_RESULT",
	"SMSG_ITEM_APPLICATION_UPDATE",
	"SMSG_ITEM_APPLICATION_UPDATE_ALL",
	"SMSG_ITEM_COOLDOWN_LIST",
	"SMSG_ITEM_ACTION_MESSAGE",
};

// World Opcode Handlers
std::unordered_map<uint16, OpcodeHandler> gOpcodeHandlerTable = 
{
	{ CMSG_PLAYER_LOGIN,					{ STATUS_AUTHED,		&WorldSession::handlePlayerLogin				} },
	{ CMSG_PLAYER_LOGOUT,					{ STATUS_LOGGEDIN,		&WorldSession::handlePlayerLogout				} },
	{ CMSG_JOIN_THEATER,					{ STATUS_AUTHED,		&WorldSession::handleJoinTheater				} },
	{ CMSG_QUERY_CHARACTER_INFO,			{ STATUS_LOGGEDIN,		&WorldSession::handleQueryCharacterInfo			} },
	{ MSG_MOVE_START,						{ STATUS_LOGGEDIN,		&WorldSession::handleMovementInfo				} },
	{ MSG_MOVE_SYNC,						{ STATUS_LOGGEDIN,		&WorldSession::handleMovementInfo				} },
	{ MSG_MOVE_HEARTBEAT,					{ STATUS_LOGGEDIN,		&WorldSession::handleMovementInfo				} },
	{ MSG_MOVE_TURN,						{ STATUS_LOGGEDIN,		&WorldSession::handleMovementInfo				} },
	{ MSG_MOVE_STOP,						{ STATUS_LOGGEDIN,		&WorldSession::handleMovementInfo				} },
	{ CMSG_ATTACK,							{ STATUS_LOGGEDIN,		&WorldSession::handleAttackInfo					} },
	{ MSG_CHARGE_START,						{ STATUS_LOGGEDIN,		&WorldSession::handleStaminaInfo				} },
	{ MSG_CHARGE_STOP,						{ STATUS_LOGGEDIN,		&WorldSession::handleStaminaInfo				} },
	{ MSG_STAMINA_SYNC,						{ STATUS_LOGGEDIN,		&WorldSession::handleStaminaInfo				} },
	{ CMSG_QUERY_WORLD_STATUS,				{ STATUS_LOGGEDIN,		&WorldSession::handleQueryWorldStatus			} },
	{ CMSG_QUERY_THEATER_STATUS_LIST,		{ STATUS_LOGGEDIN,		&WorldSession::handleQueryTheaterStatusList		} },
	{ CMSG_SMILEY_CHAT,						{ STATUS_LOGGEDIN,		&WorldSession::handleSmileyChat					} },
	{ CMSG_QUERY_PLAYER_STATUS_LIST,		{ STATUS_LOGGEDIN,		&WorldSession::handleQueryPlayerStatusList		} },
	{ CMSG_GM_COMMAND,						{ STATUS_LOGGEDIN,		&WorldSession::handleGMCommand					} },
	{ CMSG_USE_ITEM,						{ STATUS_LOGGEDIN,		&WorldSession::handleUseItem					} },
};

