// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogonResult.proto

#ifndef PROTOBUF_LogonResult_2eproto__INCLUDED
#define PROTOBUF_LogonResult_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
class LogonResult;
class LogonResultDefaultTypeInternal;
extern LogonResultDefaultTypeInternal _LogonResult_default_instance_;

namespace protobuf_LogonResult_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_LogonResult_2eproto

enum LogonResult_AuthResult {
  LogonResult_AuthResult_AUTH_OK = 0,
  LogonResult_AuthResult_AUTH_FAILED = 1,
  LogonResult_AuthResult_LogonResult_AuthResult_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  LogonResult_AuthResult_LogonResult_AuthResult_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool LogonResult_AuthResult_IsValid(int value);
const LogonResult_AuthResult LogonResult_AuthResult_AuthResult_MIN = LogonResult_AuthResult_AUTH_OK;
const LogonResult_AuthResult LogonResult_AuthResult_AuthResult_MAX = LogonResult_AuthResult_AUTH_FAILED;
const int LogonResult_AuthResult_AuthResult_ARRAYSIZE = LogonResult_AuthResult_AuthResult_MAX + 1;

enum LogonResult_ErrorCode {
  LogonResult_ErrorCode_ERROR_NONE = 0,
  LogonResult_ErrorCode_ERROR_LOW_CLIENT_VERSION = 1,
  LogonResult_ErrorCode_LogonResult_ErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  LogonResult_ErrorCode_LogonResult_ErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool LogonResult_ErrorCode_IsValid(int value);
const LogonResult_ErrorCode LogonResult_ErrorCode_ErrorCode_MIN = LogonResult_ErrorCode_ERROR_NONE;
const LogonResult_ErrorCode LogonResult_ErrorCode_ErrorCode_MAX = LogonResult_ErrorCode_ERROR_LOW_CLIENT_VERSION;
const int LogonResult_ErrorCode_ErrorCode_ARRAYSIZE = LogonResult_ErrorCode_ErrorCode_MAX + 1;

// ===================================================================

class LogonResult : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:LogonResult) */ {
 public:
  LogonResult();
  virtual ~LogonResult();

  LogonResult(const LogonResult& from);

  inline LogonResult& operator=(const LogonResult& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LogonResult(LogonResult&& from) noexcept
    : LogonResult() {
    *this = ::std::move(from);
  }

  inline LogonResult& operator=(LogonResult&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const LogonResult& default_instance();

  static inline const LogonResult* internal_default_instance() {
    return reinterpret_cast<const LogonResult*>(
               &_LogonResult_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(LogonResult* other);
  friend void swap(LogonResult& a, LogonResult& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LogonResult* New() const PROTOBUF_FINAL { return New(NULL); }

  LogonResult* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const LogonResult& from);
  void MergeFrom(const LogonResult& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LogonResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef LogonResult_AuthResult AuthResult;
  static const AuthResult AUTH_OK =
    LogonResult_AuthResult_AUTH_OK;
  static const AuthResult AUTH_FAILED =
    LogonResult_AuthResult_AUTH_FAILED;
  static inline bool AuthResult_IsValid(int value) {
    return LogonResult_AuthResult_IsValid(value);
  }
  static const AuthResult AuthResult_MIN =
    LogonResult_AuthResult_AuthResult_MIN;
  static const AuthResult AuthResult_MAX =
    LogonResult_AuthResult_AuthResult_MAX;
  static const int AuthResult_ARRAYSIZE =
    LogonResult_AuthResult_AuthResult_ARRAYSIZE;

  typedef LogonResult_ErrorCode ErrorCode;
  static const ErrorCode ERROR_NONE =
    LogonResult_ErrorCode_ERROR_NONE;
  static const ErrorCode ERROR_LOW_CLIENT_VERSION =
    LogonResult_ErrorCode_ERROR_LOW_CLIENT_VERSION;
  static inline bool ErrorCode_IsValid(int value) {
    return LogonResult_ErrorCode_IsValid(value);
  }
  static const ErrorCode ErrorCode_MIN =
    LogonResult_ErrorCode_ErrorCode_MIN;
  static const ErrorCode ErrorCode_MAX =
    LogonResult_ErrorCode_ErrorCode_MAX;
  static const int ErrorCode_ARRAYSIZE =
    LogonResult_ErrorCode_ErrorCode_ARRAYSIZE;

  // accessors -------------------------------------------------------

  // .LogonResult.AuthResult result = 1;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::LogonResult_AuthResult result() const;
  void set_result(::LogonResult_AuthResult value);

  // .LogonResult.ErrorCode error_code = 2;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 2;
  ::LogonResult_ErrorCode error_code() const;
  void set_error_code(::LogonResult_ErrorCode value);

  // @@protoc_insertion_point(class_scope:LogonResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  int result_;
  int error_code_;
  mutable int _cached_size_;
  friend struct protobuf_LogonResult_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LogonResult

// .LogonResult.AuthResult result = 1;
inline void LogonResult::clear_result() {
  result_ = 0;
}
inline ::LogonResult_AuthResult LogonResult::result() const {
  // @@protoc_insertion_point(field_get:LogonResult.result)
  return static_cast< ::LogonResult_AuthResult >(result_);
}
inline void LogonResult::set_result(::LogonResult_AuthResult value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:LogonResult.result)
}

// .LogonResult.ErrorCode error_code = 2;
inline void LogonResult::clear_error_code() {
  error_code_ = 0;
}
inline ::LogonResult_ErrorCode LogonResult::error_code() const {
  // @@protoc_insertion_point(field_get:LogonResult.error_code)
  return static_cast< ::LogonResult_ErrorCode >(error_code_);
}
inline void LogonResult::set_error_code(::LogonResult_ErrorCode value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:LogonResult.error_code)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::LogonResult_AuthResult> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::LogonResult_ErrorCode> : ::google::protobuf::internal::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_LogonResult_2eproto__INCLUDED
